package edu.hm.cs.fs.scriptinat0r7.repositories;

import static org.junit.Assert.assertEquals;

import java.util.List;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import edu.hm.cs.fs.scriptinat0r7.model.Lecture;

/**
 * Test class for the autogenerated {@code LectureRepository} implementation.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration("classpath:/spring/test-beans.xml")
public class LectureRepositoryTest {

    @Autowired
    private LectureRepository testRepo;

    /**
     * Tests if one {@code Lecture} can be found by its name.
     */
    @DirtiesContext
    /* This is optional, if the test leaves a dirty application context. */
    @Test
    public void testFindByNameContaining() {
        Lecture expected = new Lecture();
        expected.setName("Softwareentwicklung II");
        testRepo.save(expected);

        List<Lecture> actual = testRepo.findByNameContainingIgnoreCase("Softwareentwicklung");

        assertEquals("The size of the containing lectures must be exactly 1.", 1, actual.size());
    }
}
